version: '3.8'

services:
  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    command: 
      - --config.my-cnf=/cfg/.my.cnf
      - --mysqld.address=host.docker.internal:3306
    volumes:
      - "./my.cnf:/cfg/.my.cnf:ro"
    ports:
      - "9104:9104"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - mysqld-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=mr.looser37
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
